on:
  push:
    branch: "nvidia"

jobs:
  gen_iso:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/void-linux/void-linux:latest-full-x86_64
      options: --privileged
    defaults:
      run:
        shell: sh
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
      - name: Set repository
        run: |
          REPO='https://mirrors.dotsrc.org/voidlinux/current'
          # Set repository for xbps
          rm -fr /etc/xbps.d
          mkdir -p -m 755 /etc/xbps.d
          echo "repository=$REPO" > /etc/xbps.d/repo.conf
      - name: Install dependencies
        run: xbps-install --yes -S gcc bash liblz4 lzo kmod e2fsprogs
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate ISO
        run: |
          chmod +x ./gen-nvidia.sh
          ./gen-nvidia.sh
      - name: Upload ISO
        uses: actions/upload-artifact@v2
        with:
           name: void-live-x86_64-${{ steps.date.outputs.date }}-${{ github.sha }}.iso
           path: /root/void-mklive/void-live-x86_64-*.iso
